# _config.yml for Jekyll (optional, since we used .nojekyll)

# Site settings
title: Pasha Law Senate
description: Expert legal services tailored to your needs.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://your-username.github.io/pasha-law-senate" # The base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  style: compressed # Use compressed CSS if you have .scss files
  sass_dir: assets/css # Directory for Sass files (if used)

# Exclude files that aren’t needed
exclude:
  - README.md
  - .gitignore